/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      softpass.h                                 ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef IncludesFor_softpass
#define IncludesFor_softpass (1)

#define PREFER_LOCAL (1)
#define WITH_STRGPOOL
#define WITH_JUNKYARD
#include <.environMentor.h>

#ifndef SOFTPASS_STORAGE_LOCATION
#define SOFTPASS_STORAGE_LOCATION  "Storage location not set"
#endif

#ifndef SOFTPASS_USE_PASSWORDSAPI
#define SOFTPASS_USE_PASSWORDSAPI (0)
#endif

const char* softpass_get_wort(const char* usePwApi, const char* wortFuerOrt);
const char* softpass_add_wort(int usePwApi, const char* location, const char* pass);
const char* softpass_lst_alle(int usePwApi);
const char* softpass_rem_wort(int usePwApi, const char* wortFuerOrt);
const char* softpass_set_conf(const char* was,const char* das);

#ifdef _OnTheFly_
#include ".softpass.cc"
#endif
#endif
