#!/usr/bin/tcc -run -w
/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      softpass.c                                 ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#define _OnTheFly_ softpass
#define softpass ""
#include ".softpass.h"
int main(int argc,char** argv);
